name: Release

on:
  push:
    tags:
      - v*  # matches version tags: v1.0.1, v2, etc

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install wheel
        pip install setuptools twine
    - name: Build project
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish project
      run: |
        twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
