name: Tests

on: [push, pull_request]

jobs:

  unit_tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: dependencies
      run: |
        pip install wheel
        pip install pytest
        pip install -e .
    - name: unit tests ${{ matrix.os }} - ${{ matrix.python-version }}
      run: |
        pytest tests/unit/

  integration_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      pebble:
        image: letsencrypt/pebble
        ports:
          - 14000:14000

    steps:
    - name: setup localhost aliases
      run: |
        echo "127.0.0.1 autocert.example.org www.autocert.example.org" | sudo tee -a /etc/hosts
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: dependencies
      run: |
        pip install wheel
        pip install pytest
        pip install -e .
    - name: integration tests ${{ matrix.python-version }}
      run: |
        pytest tests/integration/
